type Translation {
  lang: String!
  translations: String!
}

type Product {
  id: Int!
  categoryKeyPath: String!
  pageUrl: String!
  name: String!
  price: Float!
  taxRate: Float
  description: String
}

type Query {
  allTranslations: [Translation!],
  allProducts: [Product!]
}
